### PR TITLE
ci: update cert-manager

### PR DESCRIPTION
**Pull request by Gala-R**
update cert-manager

### CODE REVIEW

**Comment by Rory-Z** [comment]
`.github/workflows/test.yaml` and `.github/actions/deploy-operator/action.yaml` also need to be modify

**Comment by Rory-Z** [comment]
Commit log need more detail, like "ci: dump cert-manger version to 1.8.2"

**Comment by Gala-R** [comment]
modifed

**Comment by Rory-Z** [comment]
> modifed

**Review by Rory-Z — CHANGES_REQUESTED** [review]
.github/workflows/test.yaml and .github/actions/deploy-operator/action.yaml also need to be modify

**Comment by Gala-R** [comment]
done all!

**Review by Rory-Z — APPROVED** [review]

**Pull request merged**
