### PR TITLE
fix: fix fs permission error

### PR DESCRIPTION
**Pull request by kiragoo**

### CODE REVIEW

**Comment by Rory-Z** [comment]
Why we need this ？

**Comment by Rory-Z** [comment]
This is a bug ？

**Comment by kiragoo** [comment]
> This is a bug ？

Allocating an FSGroup that owns the pod's volumes	[fsGroup](https://kubernetes.io/docs/concepts/security/pod-security-policy/#volumes-and-file-systems).
While creating pv by sc,the default group of user is root cause the permission error for user in emqx user group.

**Review by brianbinbin — APPROVED** [review]

**Comment by Rory-Z** [comment]
I think we should put the SecurityContext in the CRD "spec.emqxTemplate" and let the users configure it themselves, since not all users are using the official emqx image, r

**Pull request merged**
