### PR TITLE
docs: add service task doc

### PR DESCRIPTION
**Pull request by Gala-R**

### CODE REVIEW

**Review by Rory-Z — COMMENTED** [review]
I think we should add an introduction to "EMQX Operator auto-discovers listeners and binds them"

**Comment by Rory-Z** [comment]
docs/directory.json

**Comment by Gala-R** [comment]
> 



> I think we should add an introduction to "EMQX Operator auto-discovers listeners and binds them"

I agree with your idea, I will introduce emqx-operator to automatically discover listeners and binds  in the document

**Comment by Gala-R** [comment]
> Don't forget update `docs/directory.json`
As I remember, I'll update `docs/directory.json`

**Pull request closed without merging**
